### ISSUE TITLE
TypeError: Cannot read property 'pathname' of undefined (3.0.0-rc22)

### ISSUE THREAD

**Issue by jazzido** [bdefore/redux-universal-renderer#65]
After upgrading to 3.0.0-rc22:

```
TypeError: Cannot read property 'pathname' of undefined
[1]     at locationsAreEqual (/Users/manuel/Work/spendview/webapp/node_modules/history/lib/createHistory.js:42:26)
[1]     at Object.transitionTo (/Users/manuel/Work/spendview/webapp/node_modules/history/lib/createHistory.js:143:21)
[1]     at /Users/manuel/Work/spendview/webapp/node_modules/react-router-redux/lib/index.js:114:17
[1]     at /Users/manuel/Work/spendview/webapp/node_modules/redux/lib/createStore.js:132:14
[1]     at Array.forEach (native)
[1]     at dispatch (/Users/manuel/Work/spendview/webapp/node_modules/redux/lib/createStore.js:131:23)
[1]     at /Users/manuel/Work/spendview/webapp/node_modules/react-router-redux/lib/index.js:87:18
[1]     at fetcher.js:56:9
[1]     at Function.reduxAsyncConnect (Home.js:28:16)
[1]     at /Users/manuel/Work/spendview/webapp/node_modules/redux-async-connect/lib/ReduxAsyncConnect.js:93:22
```

**Comment by bdefore** [comment]
@jazzido As of rc22, UR uses `react-router-redux` 2.1.0 rather than `redux-simple-router` 2.0.3 (the project was renamed). You may need to update this in your reducers index.

**Comment by jazzido** [comment]
Yep, that was it. Thanks for an awesome package (also, thanks a lot for 13963029bc8d4fdb5c5d7d8658a8163f991d4d10)
