### ISSUE TITLE
Getting error on running example/jwt

### ISSUE THREAD

**Issue by tarkanlar** [bdefore/redux-universal-renderer#8]
I am getting error on the jwt example

this is my console log

[3] to be executed: node ./bin/start
[1] ==> 💻  API server running at http://localhost:3000/v1
[2] ==> 💻  Authentication server running at undefined:undefined

...
..
 saveUninitialized: false } ]
[3] Sun, 20 Dec 2015 15:47:14 GMT express-session deprecated req.secret; provide secret option at node_modules/express-jwt-proxy/lib/index.js:210:45
[3] universal-redux configuration is valid.
[3] events.js:141
[3]       throw er; // Unhandled 'error' event
[3]       ^
[3]
[3] Error: listen EADDRINUSE :::3000
[3]     at Object.exports._errnoException (util.js:855:11)
[3]     at exports._exceptionWithHostPort (util.js:878:20)
[3]     at Server._listen2 (net.js:1237:14)
[3]     at listen (net.js:1273:10)
[3]     at Server.listen (net.js:1369:5)
[3]     at EventEmitter.listen (/Users/anlar/Dev/universal-redux/examples/jwt/node_modules/express/lib/application.js:617:24)
[3]     at Object.<anonymous> (/Users/anlar/Dev/universal-redux/examples/jwt/bin/start_es6.js:15:3)
[3]     at Module._compile (module.js:398:26)
[3]     at normalLoader (/Users/anlar/Dev/universal-redux/examples/jwt/node_modules/babel-core/lib/api/register/node.js:199:5)
[3]     at Object.require.extensions.(anonymous function) [as .js](/Users/anlar/Dev/universal-redux/examples/jwt/node_modules/babel-core/lib/api/register/node.js:216:7)
[3]

**Comment by bdefore** [comment]
@tarkanlar did you remember to create an `.env` file? https://github.com/bdefore/universal-redux/tree/master/examples/jwt#configure-environment-variables

**Comment by tarkanlar** [comment]
Oh! Thanks, it worked. I am really sorry

**Comment by bdefore** [comment]
No problem @tarkanlar let me know if you run into anything else :beer:
